---
- hosts: all
  become: yes
  vars:
    app_version: "{{ app_version }}"
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "your-dockerhub-username/medicare-app:{{ app_version }}"
        source: pull
    
    - name: Run Docker container
      docker_container:
        name: medicare-app
        image: "your-dockerhub-username/medicare-app:{{ app_version }}"
        state: started
        ports:
          - "8082:8082"
