---
- hosts: all
  become: yes
  vars:
    app_version: "1.0.0"
    # Remove the redundant app_version assignment

  tasks:
    - name: Pull Docker image
      docker_image:
        name: "medicare-app:{{ app_version }}"
        source: pull
    
    - name: Run Docker container
      docker_container:
        name: medicare-app
        image: "medicare-app:{{ app_version }}"
        state: started
        ports:
          - "8080:8080"
